### ISSUE TITLE
Setting `Max` instead of `Min` in objective makes `objective_value` negative

### ISSUE THREAD

**Issue by dlcole3** [plasmo-dev/Plasmo.jl#103]
If you set the objective on a node to maximize instead of minimize, the objective value it returns will be negative. For example, in the code below, the objective value that is returned should be +2, but it is -2. 

```julia
using Plasmo, HiGHS

g = OptiGraph()
set_optimizer(g, HiGHS.Optimizer)
@optinode(g, n)
@variable(n, x <= 2)
@objective(n, Max, x)
optimize!(g)
println(objective_value(g))
```

**Comment by dlcole3** [comment]
Just double checked and this is still occurring in v0.6.0.

**Comment by jalving** [comment]
Thanks for checking this again. I'll get this fixed soon.

**Comment by jalving** [comment]
In this case, the graph assumes a `Min` sense by default. If I run this code:
```julia
using Plasmo, HiGHS

g = OptiGraph()
set_optimizer(g, HiGHS.Optimizer)
@optinode(g, n)
@variable(n, x <= 2)
@objective(n, Max, x)
set_to_node_objectives(g)
optimize!(g)

println("graph objective function:", objective_function(g))
println("graph objective value:", objective_value(g))
println("node objective function", objective_function(n))
println("node objective value", value(objective_function(n)))
```
I get as expected:
```
graph objective function:-n[:x]
graph objective value:-2.0
node objective functionn[:x]
node objective value2.0
```
I think this makes sense as default behavior since nodes could have either objective sense. If a user wants to specify a graph objective, then can use `@objective(g, Max, n[:x]`)

**Comment by jalving** [comment]
does that make sense @dlcole3?

**Comment by dlcole3** [comment]
> does that make sense @dlcole3?

Yep, that does make sense.
