### ISSUE TITLE
append_to_backend accesses private methods from MOI.Utilities

### ISSUE THREAD

**Issue by odow** [plasmo-dev/Plasmo.jl#104]
See

https://github.com/plasmo-dev/Plasmo.jl/blob/fb7bda514057c5b51205504fb79faef2c8c83562/src/moi_backend_graph.jl#L126-L152

x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2520

**Comment by jalving** [comment]
Thanks for the heads up. I will be rolling out a new version soon that uses no private MOI methods.

**Comment by odow** [comment]
I'm reverting the change to MOI that removed them, so you're good for a while.

**Comment by jalving** [comment]
Plasmo.jl *should* no longer be using private MOI methods with v0.6, but please re-open if you spot an instance i missed.

Addressed with #105
