### ISSUE TITLE
@variable and @constraint macros are very slow when defining over sets in v0.6

### ISSUE THREAD

**Issue by dlcole3** [plasmo-dev/Plasmo.jl#114]
The `@variable` and `constraint` macros seem really slow under the new version of Plasmo when defining over sets. For example, the last line below in Plasmo v0.5.4 runs in <0.1 seconds, but it runs in >5 seconds in Plasmo v0.6.1.

```julia
using Plasmo, JuMP

g = OptiGraph()

X = 100
Y = 100

@optinode(g, n)
@time @variable(n, x[1:X, 1:Y] >= 0);
```

Perhaps it has something to do with how the names are set. When I run the code below, it takes approximately the same amount of time in both v0.5.4 and v0.6.1.

```julia
@time begin
    for i in 1:X
        for j in 1:Y
            @variable(n)     
        end
    end
end
```

I believe the same problem arises with constraints based on some other code I am running.

**Comment by jalving** [comment]
should be fixed by #116
