### ISSUE TITLE
Need to update install instructions

### ISSUE THREAD

**Issue by etatara** [plasmo-dev/Plasmo.jl#14]
The readme indicates using Pkg.add("Plasmo.jl"), however this does not work.  Pkg.add("Plasmo") does work but installs v.0.2.  To clone the latest master with Julia 1.4.2+, the following is needed:

Pkg.add(PackageSpec(url="https://github.com/zavalab/Plasmo.jl"))

**Comment by jalving** [comment]
Thanks for catching this Eric.  In order to fix Pkg.add("Plasmo.jl"), I just need to finish updating the compatibility section in the Project file.  Then the Julia registry will accept v0.3.0.  I should have this done tomorrow.

**Comment by jalving** [comment]
Can you try adding Plasmo again?  It should pull v0.3.0 now.

**Comment by etatara** [comment]
Yes, using Pkg.add("Plasmo") does install v.0.3.  I suggest updating the README.md since it says to use Pkg.add("Plasmo.jl") - and I don;t think that worked with v.0.2 either.

**Comment by jalving** [comment]
Nice catch, I went ahead and fixed that in the master.  Plasmo.jl installation seems to be working as intended now.
