### ISSUE TITLE
Project.toml compat is out of date

### ISSUE THREAD

**Issue by pulsipher** [plasmo-dev/Plasmo.jl#24]
The compat dependencies need to be updated. For instance, DataStructures is limited to `~0.17` but the current version of JuMP exacts that `0.18` be used. One suggestion to help keep up to date is to use [CompatHelper.jl](https://github.com/JuliaRegistries/CompatHelper.jl) to automate this process.

**Comment by jalving** [comment]
The Project.toml was updated for the latest release (v0.3.3).  Thanks for the suggestion.  I will look into incorporating CompatHelper.jl to keep dependencies up to date.
