### ISSUE TITLE
Better graph show

### ISSUE THREAD

**Issue by bbrunaud** [plasmo-dev/Plasmo.jl#4]
We need a better show function for graphs, it needs to indicate the type of graph, the nodes, and edges.

```julia
julia> typeof(g)
Plasmo.PlasmoModels.ModelGraph

julia> g
graph_id: ##816
lightgraph:Plasmo.PlasmoGraphBase.HyperGraph([1, 2], Plasmo.PlasmoGraphBase.AbstractHyperEdge[Hyper Edge (1, 2)], Dict(2=>Plasmo.PlasmoGraphBase.AbstractHyperEdge[Hyper Edge (1, 2)],1=>Plasmo.PlasmoGraphBase.AbstractHyperEdge[Hyper Edge (1, 2)]))
```

**Comment by jalving** [comment]
ModelGraph has now been deprecated in favor of OptiGraph.  The OptiGraph show gives both local and total nodes, edges, and subgraphs. Feel free to open a new issue if you have other suggestions.
