### ISSUE TITLE
some redirects from `zavalab` to `plasmo-dev` don't work

### ISSUE THREAD

**Issue by anhinga** [plasmo-dev/Plasmo.jl#67]
In the README.md, https://zavalab.github.io/Plasmo.jl/dev/ should redirect to https://plasmo-dev.github.io/Plasmo.jl/dev/

In https://plasmo-dev.github.io/Plasmo.jl/dev/tutorials/gas_pipeline/, https://github.com/zavalab/PlasmoExamples does not redirect to https://github.com/plasmo-dev/PlasmoExamples

**Comment by jalving** [comment]
Thanks for catching these. Some of the links got missed when we migrated the project to plasmo-dev. I'll update these when I get a minute.
