### ISSUE TITLE
Using a solver other than Ipopt

### ISSUE THREAD

**Issue by nazir-nawaf** [plasmo-dev/Plasmo.jl#70]
Hi, I've just started to use Plasmo.jl and have been going through some of the example code. My issue is that when I try to use a solver other than Ipopt, I get the following error:

LoadError: MathOptInterface.GetAttributeNotAllowed{MathOptInterface.NLPBlockDual}: Getting attribute MathOptInterface.NLPBlockDual(1) cannot be performed: Gurobi.Optimizer does not support getting the attribute MathOptInterface.NLPBlockDual(1). You may want to use a `CachingOptimizer` in `AUTOMATIC` mode or you may need to call `reset_optimizer` before doing this operation if the `CachingOptimizer` is in `MANUAL` mode.

In this case I'm trying to use Gurobi, but I get this error with every solver, even GLPK. Can you please help me out on what I'm doing wrong?

**Comment by jalving** [comment]
Hi @nazir-nawaf. This should be fixed with the latest release. Can you try updating Plasmo.jl and re-testing?

**Comment by nazir-nawaf** [comment]
Hi @jalving. Yes it's working now. Thank you!!
