### ISSUE TITLE
`aggregate` throws an error for some OptiGraphs when `max_depth` > 0

### ISSUE THREAD

**Issue by dlcole3** [plasmo-dev/Plasmo.jl#76]
I found that I am getting an error when trying to aggregate a problem with a `max_depth` of 1. I believe the issue is coming because the variable `nodes` in [this line](https://github.com/plasmo-dev/Plasmo.jl/blob/ba8520a9dd3d29c9a9d3f2c5d3f1ddbbae3d7bcc/src/aggregate.jl#L273) has a length of 0. For the problem I am working on, I have an OptiGraph with subgraphs where all OptiNodes are contained on the subgraphs. Consequently, `optinodes(graph)` is empty since it appears that `optinodes` only gets the OptiNodes defined on the highest layer. Below is a minimum working example that returns the same error that I am getting. 

```
using Plasmo

graph0 = OptiGraph()

graph1 = OptiGraph()
graph2 = OptiGraph()

@optinode(graph1, node1)
@variable(node1, 0 <= x)
@optinode(graph2, node2)
@variable(node2, 0 <= x)

add_subgraph!(graph0, graph1)
add_subgraph!(graph0, graph2)

@linkconstraint(graph0, graph1[:node1][:x] + graph2[:node2][:x] >= 1)

println(length(optinodes(graph0)) == 0)

agg_1, extras = Plasmo.aggregate(graph0, 1)
```

**Comment by jalving** [comment]
thanks for reporting this. I will take a look soon.
